---
- name: update web servers
  hosts: ubuntu
  become: yes
  tasks:
  - name: ensure apache2 is installed
    package:
      name: apache2
      state: present

  - name: ensure apache2 is started
    service:
      name: apache2
      state: started

  - name: ensure apache2 is enabled
    service:
      name: apache2
      enabled: yes
...
