---

- name: update web servers
  hosts: ubuntu
  become: yes

  tasks:
  - name: ensure apache2 is installed
    package:
      name: apache2
      state: present
    notify:
      - Remove Index
      - ensure site

  - name: ensure apache2 is started
    service:
      name: apache2
      state: started

  - name: ensure apache2 is enabled
    service:
      name: apache2
      enabled: yes
  
  handlers:
  - name: Remove Index
    file:
      path: /var/www/html/index.html
      state: absent

  - name: ensure site
    git:
      repo: https://github.com/clairejoseph0103/ecomm.git
      dest: /var/www/html


...
