---
- name: update web servers
  hosts: all
  become: yes

  tasks:
  - name: WebPage-Static
    copy:
      src: dynamic.j2 
      dest: /var/www/html/dynamic.html

  - name: WebPage-Dynamic
    template:
      src: dynamic.j2
      dest: /var/www/html/dynamic_info.html
...

