---
  - name: Ensure Site
    git:
      repo: https://github.com/clairejoseph0103/ecomm.git
      dest: /var/www/html

  - name: Restart HTTPD
    service:
      name: httpd
      state: restarted

  - name: Ensure web server is started
    service:
      name: httpd
      state: started

...

