---
  - name: SELinux Permissive
    selinux:
      policy: targeted
      state: permissive

  - name: Ensure web server is enabled
    service:
      name: httpd
      enabled: yes

  - name: Ensure web server is started
    service:
      name: httpd
      state: started

  - name: Modify Port
    template:
      src: httpd.j2
      dest: /etc/httpd/conf/httpd.conf
    notify:
    - Restart HTTPD

  - name: Update PHP app
    copy:
      src: date.php
      dest: /var/www/html/date.php




...

